version: "3.9"

services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE

  backend:
    build: ./backend
    volumes:
      - ./backend/:/src
    ports:
      - "8080:8080"
    depends_on:
      - chroma
    command: python /src/manage.py runserver 127.0.0.1:8080

  frontend:
    build:
      context: ./frontend
      target: dev # dev for development build, production for production build
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: always
    depends_on:
      - chroma
      - backend
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  data:
