# docker-compose.yml
version: "3.9"

services:
  db:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - data:/chroma/chroma

  app:
    image: autogen_img
    volumes:
      - ./src/:/src
    depends_on:
      - db

volumes:
  data:
