version: "3.9"

services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE

    # backend:
    #   build: ./backend
    #   volumes:
    #     - ./backend/:/backend
    #   ports:
    #     - "8080:8080"
    #   depends_on:
    #     - chroma
    #   command: python /backend/manage.py runserver
    #
    # frontend:
    #   build: ./frontend
    #   volumes:
    #     - ./frontend/src/:/app/src
    #     - ./frontend/src/public/:/app/public
    #   restart: always
    #   depends_on:
    #     - chroma
    #   ports:
    #     - "3000:3000"
    #   command: npm run start

  llm:
    build: ./backend
    volumes:
      - ./backend/llm/:/src/llm
    depends_on:
      - chroma
    command: ["pwd", "&&", "ls", "-l"]

volumes:
  data:
